### ISSUE TITLE
Rewrite the git repository to remove large files from history

### ISSUE THREAD

**Issue by ylep** [populse/soma-base#1]

**Comment by denisri** [comment]
git filter-branch --force --index-filter 'git rm -f --cached --ignore-unmatch python/doc/source/_static/clustering.gif doc/pipeline/pres_club_dev_end.pdf python/soma/sandbox/NotationGUI/HumanBrain.jpg python/soma/sandbox/NotationGUI/Earth.png python/soma/sandbox/NotationGUI/fire.png python/doc/source/_themes/scikit-learn/static/css/bootstrap.css share/icons/add_files.png share/icons/delete_files.png python/doc/source/_themes/scikit-learn/static/css/bootstrap.min.css python/soma/sandbox/NotationGUI/xlrd/sheet.py python/soma/sandbox/NotationGUI/xlrd/doc/xlrd.html python/soma/sandbox/NotationGUI/xlwt/BIFFRecords.py python/doc/source/_themes/scikit-learn/static/jquery.js python/soma/sandbox/NotationGUI/xlrd/formula.py python/soma/pipeline/pres_club_dev_end.pdf' --tag-name-filter 'cat' -- --all
