### ISSUE TITLE
pydantic_controller discussion

### ISSUE THREAD

**Issue by denisri** [populse/soma-base#19]
I open this ticket to discuss the API and first issues related to the new `pydantic_controller` branch.

**Comment by denisri** [comment]
I'm not familiar with the python3 typing syntax yet so I may write silly comments...
The first things I see is when I instantiate a `Controller` class with a field which doesn't have a value, I cannot print it:
```
from soma.controller import controller
class Bibi(controller.Controller):
    toto: int

b = Bibi()
b

>>>
AttributeError                            Traceback (most recent call last)
/usr/lib/python3/dist-packages/IPython/core/formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

/usr/lib/python3/dist-packages/IPython/lib/pretty.py in pretty(self, obj)
    392                         if cls is not object \
    393                                 and callable(cls.__dict__.get('__repr__')):
--> 394                             return _repr_pprint(obj, self, cycle)
    395 
    396             return _default_pprint(obj, self, cycle)

/usr/lib/python3/dist-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    698     """A pprint that just redirects to the normal repr function."""
    699     # Find newlines and replace them with p.break_()
--> 700     output = repr(obj)
    701     lines = output.splitlines()
    702     with p.group():

/usr/lib/python3.9/dataclasses.py in wrapper(self)
    368         repr_running.add(key)
    369         try:
--> 370             result = user_function(self)
    371         finally:
    372             repr_running.discard(key)

/casa/host/build/python/soma/controller/controller.py in __repr__(self)

/casa/host/build/python/soma/controller/controller.py in __getattribute__(self, name)
    226             result = super().__getattribute__(name)
    227         if result is undefined:
--> 228             raise AttributeError('{} object has no attribute {}'.format(repr(self.__class__), repr(name)))
    229         return result
    230 
```
Is it an "expected behaviour" ? It's not very convenient...
`b.asdict()` works, however. I understand `asdict()` replaces `export_to_dict()` in the older `Controller` class, and it comes from the python `dataclass`, right ?

**Comment by denisri** [comment]
Next, controller.field() objects don't behave the same in class and instance attributes, and thus the syntax of `field()` is not clear to me:
```
class class Bibi(controller.Controller):
    babar: str = controller.field(optional=True, output=True, default='babarup')

b = Bibi()
b.babar
>>>
'babarup'
```
Here, OK. Now:
```
b.add_field('blop', controller.field(type_=str, optional=True, output=True, default='babarup'))
b.blop = 'gogo'
>>>
AttributeError                            Traceback (most recent call last)
<ipython-input-118-5d1ea7b2c1f5> in <module>
----> 1 b.blop = 'gogo'

/casa/host/build/python/soma/controller/controller.py in __setattr__(self, name, value)
    239                     self.on_attribute_change.fire(name, new_value, old_value, self)
    240             else:
--> 241                 self._unnotified_setattr(name, value)
    242         else:
    243             super().__setattr__(name, value)

/casa/host/build/python/soma/controller/controller.py in _unnotified_setattr(self, name, value)
    253         dyn_field = super().__getattribute__('_dyn_fields').get(name)
    254         if dyn_field:
--> 255             setattr(dyn_field, name, value)
    256         else:
    257             field = self.__dataclass_fields__[name]
```
I suppose I didn't use it the right way, but the add_field() function doesn't produce any error. Is `field()` reserved for class attributes ?

**Comment by sapetnioc** [comment]
There are still feautures in new controllers that must be reimplemented. I just never used controllers interactively so I missed printing bug. I focused on making main tests working. The printing bug means that we must add a test for it.

**Comment by sapetnioc** [comment]
No `field` must supported for instance fields too. In your example you could pass the `fields` parameters directly to add_field but it should work also as you did it. I'll check that.

**Comment by sapetnioc** [comment]
I forgot to add this issue in the commit comment but the bug with fields is fixed

**Comment by sapetnioc** [comment]
FYI: what I do for now for testing the `pydantic_controller` branch is `python -m soma.controller.tests.test_controller`.

**Comment by denisri** [comment]
Tests are not passing using python 3.9. In `field.py`, in function `type_str(type_)`:
```
        elif name == 'Dict':
            name = 'dict'
            args = getattr(type_, '__args__', None)
            ignore_args = args == Dict.__args__
        elif name == 'Set':
            name = 'set'
            args = getattr(type_, '__args__', None)
            ignore_args = args == Set.__args__
```
`Dict` and `Set` do not have `__args__`.

**Comment by denisri** [comment]
soma-base tests fail:
```
python -m soma.tests.test_soma_base
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/casa/host/build/python/soma/tests/test_soma_base.py", line 71, in <module>
    res = is_valid_module()
  File "/casa/host/build/python/soma/tests/test_soma_base.py", line 61, in is_valid_module
    is_valid = run_all_tests()
  File "/casa/host/build/python/soma/tests/test_soma_base.py", line 50, in run_all_tests
    tests = load_pilots(module_path, module_path)
  File "/casa/host/build/python/soma/tests/load_pilots.py", line 32, in load_pilots
    sub_pilots = load_pilots(root, os.path.join(path, fname))
  File "/casa/host/build/python/soma/tests/load_pilots.py", line 48, in load_pilots
    __import__(module_name)
  File "/casa/host/build/python/soma/tests/test_fom.py", line 10, in <module>
    from soma import application
  File "/casa/host/build/python/soma/application.py", line 20, in <module>
    class Application(Singleton, Controller):
  File "/casa/host/build/python/soma/controller/controller.py", line 100, in __new__
    raise TypeError('Controller must be the first base class')
TypeError: Controller must be the first base class
```
Why is it required that `Controller` is the first base class ? I fear it could be a problem at several places in our codes, couldn't it ?
On the other hand, if I inverse the inheritance order of `Application`: `Application(Controller, Singleton)`, we get another error:
```
from soma import application
app = application.Application()
>>>
[...]
AttributeError: 'Application' object has no attribute '_dyn_fields'
```

**Comment by sapetnioc** [comment]
I did not tried with Python 3.9. Since they introduced `list[..]` and `dict[...]`, the way to inspect the parameters have changed. I will have to write version specific code here. 

Well dataclasses or Pydantic classes inheritance is a nightmare if one wants to override some of the behavior of the class. They are closed to immutable classes that cannot be modified. Therefore, I chose to dynamically create a class that derive from both Controller and then from the dataclass (with controller first). I have to manage this for derived classes, removing the controller class, building a derived dataclass and creating the new class with a Controller in first base class. It was easier to start by assuming that the controller is the first base class. But I can improve this as long as there is only one Controller in base classes.

**Comment by sapetnioc** [comment]
It was easier than I thought to fix.

**Comment by sapetnioc** [comment]
Tests are fixed on 3.9

**Comment by denisri** [comment]
Nice ;)
I forgot to mention #19 in d310742b9578315f1d201bebc6a9d4df30f36a16

**Comment by sapetnioc** [comment]
Question : How to serialize a Controller ?
I am implementing a BrainVISA use case in the new Capsul API. So my real question is how to serialize a Process. But If a controller is serializable, I have an answer. A controller is composed of three things:

1. A class
2. Custom fields
3. Fields values

I consider that, to be serializable, a Controller must be in a module accessible in the Python path. Therefore, the class will be serializable with a string: `{module}.{attribute}`. Note that `soma.controller.Controller` is valid for fully dynamic controllers. Knowing the fields types, I think JSON is an appropriate format for serialization/deserialization. But even if we go to JSON, we have to choose the format of the content. I propose the following pattern:
```
{
    "definition" : string containing the Controller class location,
    "fields": dictionary with instance fields definition (a list of parameters to give to add_field())
    "values": values of the fields (both class fields and instance fields)
}
```

**Comment by denisri** [comment]
A `Process` is supposed to do processing, so cannot be defined completely on-the-fly: it has to be a class or a wrapped function, so you are right: it has to be defined in a module, or at least a .py file, using _code_.
For a `Controller` we could decide that we want to be able to define it on the fly, then save it, but for now I don't think we have a real use case for it. So I'm also OK to require a python code file somewhere which defines the fields, types etc. Thus "saving" a Controller or a Process needs saving its class location, and fields values. Fields definition is optional in this context (moreover could add some contradictory duplicates). As you propose to save instance fields definition, then yes why not, but even those may be defined in a module code - I don't really mind...
For the format, we could prefer yaml to json ?

**Comment by sapetnioc** [comment]
Only instance fields definition will be serialized, because they are created on the fly. Class fields must not be serialized.
I really prefer yaml over json when manual editing is involved. But it comes with a really significative read performance drop in Python. Since the main use case is serialization without human intervention, I think json is a better choice. But if we accept a json-compatible dictionary, we can very easily allow the use of Yaml in some contexts.

**Comment by denisri** [comment]
OK

**Comment by denisri** [comment]
There is a somewhat painful side-effect in using the new `Controller`: the `undefined` value.
Using the former traits implementation, we could test for instance: `if controller.parameter in (Undefined, None):`
Using the new `typing` implementation, the field doesn't really take the `undefined` value, but disappears and accessing the value may trigger an exception. Thus accessing any field (especially any optional field, which may have a _perfectly legal_ `undefined` value) needs a `try...except` block, or needs the sytematic use of `getattr(object name, undefined)`, which will be needed in thousands and thousands of places, will make the code messy and difficult to read, and painful to write.
I think this will be a real burden.
Reading the code I see that this behaviour is in `Controller` implementation:
```
    def __getattribute__(self, name):
        # [...]
        if result is undefined:
            raise AttributeError('{} object has no attribute {}'.format(repr(self.__class__), repr(name)))
        return result
```
Should we really use it this way, or should we change the behaviour to return `undefined` without firing an exception (maybe at least for optional fields) ?

**Comment by sapetnioc** [comment]
Yes, I decided that there is no more legal undefined value. Therefore `undefined` must only be used as input (often as a default parameter value) but never returned or used in a container (list, dict, etc.). The firs goal was to avoid to get some `undefined` appearing deep in some structures (e.g. when converting Controller to dict) that were hard to find and requiring a test of all values when using these structures. But I also think is more Pythonic that way.

But we can make a compromise to avoid to change all code. This optional problem with many code concerns only Capsul, not soma-base. Therefore we could make a change on `Process` to make sure that all optional fields have a default value (`None` for instance).

By the way, it is possible to define an optional value in a standard way using `typing.Optional[type]`. However, this is not supported yet by soma-base. What should we be doing about it ? Keep only our metadata-based way of defining optional ? Switch to the standard way ? Support both ?

**Comment by denisri** [comment]
I don't really know... The exact meaning of `None` and `undefined` is not always so clear, and generally so mixed-up that in capsul/master most of the time we test things like this: `if value in (None, Undefined): ...` but this was probably a lack of clarity. As `None` may sometimes be a valid value, I'm not sure we can use it as a standard default, missing value. But I don't have a counter-example right here, so I'm not sure it's worth the complication...

> But I also think is more Pythonic that way.

This is not very obvious also, and can be discussed. If the possibility of the exception forces us to systematically access variables using `getattr(obj, name, None)` instead of `obj.name`, the use of it will not be pythonic at all.
If the only reason for the exception is to ease the serialization of `Controller` objects into dicts, this is rather an internal serialization matter, and doesn't justify that everyone writes code using `getattr()`. But there are also advantages in the new behaviour, like making very clear that some mandatory value is actually missing, thus making the `Controller`/`Process` invalid for execution.
Using a different default value (which may be something different from `None` and `undefined`) for optional fields could be an option, but we would need to test this other additional value at many places also.

**Comment by denisri** [comment]
**Question about lists:**
Using traits, a List of specific elements type was specified using an "inner trait", which had every needed metadata. Using pydantic, (as far as I understand) there is only one `Field` instance for the list, and items cannot be assiated with metadata.
For instance how do we manage a list of filenames ?
I can build:
```
c = Controller()
c.add_field('a', List[file(file_meta='meta_for_file')], list_meta='meta_for_list')
```
(note that we must use `List`, not `list`, because `list[file()]` produces an error, which is, in itself, an issue)
then:
```
c.metadata('a')
{'format': 'path/file',
 'dataset': 'input',
 'read': True,
 'write': False,
 'file_meta': 'meta_for_file',
 'order': 1000066,
 'list_meta': 'list_meta',
 'class_field': False}
```
thus all metadata are merged at the list level, and we have no easy way of knowing that the field is a list of files: the `field_type` is `List[str]`. Moreorver as metatada are merged on the list field, we have:
```
print(c.is_path('a'))
True
```
which means that the list of files is considered to be a file, which is the only way currently (I guess) to know that the list items are files. But the list itself is not - thus many codes need to do things like:
```
if c.is_path('a') and os.path.exists(c.a): ...
```
which causes an error here.

**Comment by sapetnioc** [comment]
My guess is that the solution to this problem (as well as for the
list[file()] issue) woul be to create types derived from str for Path, File
and Directory. Being real types, they could have their own type related
info (format, read/write access, etc.) and field metadata would be used
only for the list part.

**Comment by sapetnioc** [comment]
After some tests and discussions, it was a bit too tricky to implement `str` derived types. I changed the functions `is_path()`, `is_file()` and `is_directory()` to accept only exact types and added the corresponding ̀has_*()` function to also accept lists of the corresponding type.

**Comment by denisri** [comment]
Thanks, it will do the trick for now...
A very small practical API detail:
* there is an increasing number of "small functions" in soma.controller.field (`is_path`, `has_path`, `is_something`, `field_type`, ...), which currently need to be imported individually in a "long" line, such as:
```
from soma.controller.field import (
    undefined, Any, is_path, has_path, is_file, has_file, is_directory,
    has_directory field_type, is_list, is_input, is_output, has_default,
    default_value, List, metadata, List, file, directory, path)
```
* we cannot easily import 
```
from soma.controller import field
```
because it would hide the `field()` function
(note also that not all these functions are exposed in `soma.controller`, at least for now)
* "short function names" like `is_output()` are often used in code as variables (`is_output = process.is_output(field)`) (same remark for `field`)
Thus we should probably rather import the field module functions in a short namespace, like for instance:
```
from soma.controller import field as sf

...
if sf.is_path(some_field): ...
```
Should we recommend programmers a convenient yet standardized way of importing it (such as the classical `np` for `numpy`), or should we rather prepare a namespace (class or submodule) in the module for it, so that we could use:
```
from soma.controller.field import sf  # or from soma.controller import sf

if sf.is_path(some_field): ...
```
?

**Comment by sapetnioc** [comment]
To date, all `Controller` related imports available for users are (or should be if some are missing) importable from `soma.controller`. So if there is only one shortcut to a module, this is the one to use. Why not go for :
```
import soma.controller as sc
```

**Comment by denisri** [comment]
OK, then let's import all names from `field` in `controller`. I can do that.

**Comment by denisri** [comment]
Some `pydantic` types are implemented as class types: for instance `conlist(str, max_items=4)` returns a class (probably a type created on-the-fly), which has class attributes for `item_type`, `min_items` and `max_items`. Field values are still lists.
I wonder if it's possible to implement our `file`, `directory` and `path` items the same way, because currently they are functions returning a `Field` instance, not a type, and we cannot use them in `list` types: `list[file()]` causes an error, and same for `Union[file(), int]` for instance. For lists we have `soma.controller.List` which works, but the builtin `list[]` would be preferable, and other types variants like `Union` don't work at all.
Moreover the "function" syntax is not consistent with the rest of types, and it makes it more difficult to write automatic converters from traits (for nipype interfaces for instance) or from Axon processes.
I don't know `pydantic` validation mechanisms however, and how this could be implemented ?

**Comment by sapetnioc** [comment]
This is the way it should be done but there is a tricky part if we want to keep values compatible with `str`. If we go for a `Path` class (derived for `File` and `Directrory`), we will probably have to find the way to say to Pydantic not to complain for string values. This may be done by using `Union[Path, str]` internally for attributes of these types but I would prefer to find a way to customize this a the class level but I do not now yet how to do that with Pydantic.
The other unusual thing is that user will never handle a Path instance but only `str` (as it is now). Technically we will probably have to use Python descriptors for `Path` attributes (descriptor = customization of a single attribute acces and modification via `__get__`, `__set__` and `__delete__` methods on the attribute value class).

**Comment by denisri** [comment]
Well I don't know either how to do it, but `pydantic` seems to make it work this way for `conlist`, for instance (custom class type, but standard `list` values), so it seemed to indicate that this is possible...?

**Comment by denisri** [comment]
Validation is done in `pydantic.dataclasses.setattr_validate_assignment()`. For me this function is implemented in C (`~/.local/lib/python3.9/site-packages/pydantic/dataclasses.cpython-39-x86_64-linux-gnu.so`) but we find a python implementation here:
https://github.com/samuelcolvin/pydantic/blob/master/pydantic/dataclasses.py
In a `Controller` object, we find either in the controller itself, or in the `_dyn_fields` contoller, in `__pydantic_model__.__fields__[field_name]`, a `ModelField` object which has a `validate()` method.
In our case (as we always use `Union[type, UndefinedClass]`), the `ModelField` object has 2 `sub_fields` which are also `ModelField`, etc.
So there muse be a means to specify validation functions.

**Comment by denisri** [comment]
OK I found it:
```
import soma.controller as sc
import pydantic

 class Babar:
    @classmethod
    def __get_validators__(cls):
        return [cls.valid_truc]
    @classmethod
    def valid_truc(cls, value, values, config, field):
        if value == 12:
            raise pydantic.ValidationError('value 12 is not allowed.')
        return str(value)

c = sc.Controller()
c.add_field('toto', Babar)
c.toto = 45
print(repr(c.toto))
'45'
c.toto = 12
-> ValidationError
```

**Comment by denisri** [comment]
Now if we implement `Path`, `File` and `Directroy` as classes this way, the `format`, `dataset`, `read`, `write` properties will be in class attributes, not in the field metadata, which may change the way we use them. I don't know if there is a means to make them appear in metadata too.

**Comment by sapetnioc** [comment]
Putting values in two different places is an open door to synchronization problems. It seems better to not use directly the values but to have dedicated methods. What about putting a custom Field class around the objects returned by controller `field()` and `fields()` (we would have to check if they are returned at other places) ? We would be able to use whatever API we want. This would add an overhead but not a big one.

**Comment by sapetnioc** [comment]
I had hard time to introduce the `Field` class. This is done now therefore I removed functions from `field` module and from `Controller`class.

**Comment by sapetnioc** [comment]
Now I can go to make `Path`, `File` and `Directory`.

**Comment by sapetnioc** [comment]
With the changes I am doing, read/write attributes are going into the `Path` class. There is no more easy way to know if a list contains a readable or writable file. What should be the behavior of `is_output` for `list[Path(...)]` and `list[list[Path(...)]]` ?

**Comment by denisri** [comment]
I guess it should parse recursively the lists until it finds a write path item.

**Comment by denisri** [comment]
I agree the access to the `read` and `write` properties (and possibly others) have become extremely complex... What are the options ?

1. don't store them in `Path` class variables, but only at field-level metadata
2. make several methods in `Field` to recursively parse sub-types (a), such as `is_readable()`, `is_writable()`, but also `format()` etc... This would slow down access to these state properties, and would limit them to a few handled by these hard-coded methods.
3. Expose or duplicate some type metadata at field build time: the `field()` function could parse types (a) and sub-types and expose some properties in the field metadata. But maybe some information would be duplicated in metadata, so let's hope they don't change.

In my opinion 3 would be the cleanest, only if such properties are exposed as proxies, and not duplicated, or made read-only. But 1 could be sufficient for our needs (?). I don't like 2 very much, both for its lack of efficiency and its hard-coded, closed implementation. Moreover these properties would not be part of metadata at all.

(a) in any case we need a way of parsing sub-types. The problem is that they can be any type: `str`, `list`, `Union`, or custom types. Some types such as `list[]` or `Union[]` have a `__args__` property which list their children sub-types, but not all types do. We can treat standard hard-coded types as we know them, and maybe look for some properties they could provide (`__args__` for container types, possibly `__metadata__` for metadata to be exposed at field level...) ?

**Comment by sapetnioc** [comment]
To date, the implementation is using 2. option. I would like to go to
something close to 3 but I think we should consider changing the way we
access metadata to allow customization and optimization when necessary. Now
that we have a custom Field class for all field access, we may get rid of
metadata method and use only direct attributes and methods. This way we can
customize anything (using properties for attributes). An interesting thing
for optimization would be to do some recursive type parsing in a lazy way.
For instance, the first use of `field.is_input` could look for potential
`Path` subtype if the field is a list. This will avoid to do this work when
fields are just used to get a name or verify that it exists.

The first step would be to define and document the API we want for fields.
It could be very close to the current with metadata used as direct field
attributes. For attributes with a predefined meaning we have the
opportunity to select the name and if it is an attribute or a method.
Attributes not defined on `Field` class would be considered as custom
metadata and would be stored Dataclass field metadata.

**Comment by denisri** [comment]
If I understand you are thinking at an API like the traits, where we access metadata on the trait itself (ie `trait.output`), but which would wrap access to underlying types/subtypes under the hood. Well, why not. But it would require some work, and probably a caching mechanism which would need storing data somewhere if we want to optimize and avoid parsing sub-types many many times (the `Field` object is a transient and temporary object thus cannot store data).
For now I will just implement -temporarily- a parsing which adds in the field metadata those parsed from subtypes, as suggested in my remark (a) above. This can (and will) be changed later because it will copy data, but I'm still doing it since the libs are broken at the moment and I want them to work a little bit. (actually I have already written the code and I will just push it).

**Comment by denisri** [comment]
I'm starting to adapt capsul to the new new new `Controller`/`Field` API, and I find it not very convenient after all: metadata are now used as `Field` attributes, which looks nice at first sight, but (1) there is no list of available metadata, and (2) trying to access a metadata that is not present raises an `AttributeError`. As most metadata are optional, we end up never being able to use the new API, like `a = field.write` because you are never sure it will not raise an exception - thus we _always_ access metadata as `getattr(field, 'write', None)`, which is not very good looking, and kind of makes the attribute thing useless in the large majority of cases. Indeed, as I modify code to use the new API, the code is more verbose and less readable than before.

I propose to make them work like traits: don't raise an exception but return `None` (or `undefined`) if the metadata is not present.
We might tune this behaviour using an optional attribute (but do we set it globally or on every field ?)

**Comment by denisri** [comment]
Oh well there is still the `metadata()` method, maybe for now the best is to use it explicitly.

**Comment by sapetnioc** [comment]
FYI : On a quest to temporarily bypass Pydantic validation, I added the possibility for controllers to use [Pydantic validators](https://pydantic-docs.helpmanual.io/usage/validators/). This was not immediate because the `Controller` metaclass is doing a lot of magic to create the real class. Note that it does not allow to bypass Pydantic validation.

**Comment by sapetnioc** [comment]
Question: I finally found a simple way to force a value that do not satisfy Pydantic validation :
```
from soma.controller import Controller, Literal

class C(Controller):
    s : Literal['only me']


o = C()
# o.s = 'not me' # raises Pydantic ValidationError
object.__setattr__(o, 's', 'not me')
print(o.s) # prints "not me"
```
Should we add a method on `Controller` to set a value unconditionally ?

**Comment by sapetnioc** [comment]
Question : @denisri already mentioned that it is annoying to use `getattr(controller, name, default)` to get a possibly missing value of a controller field. What about adding the following method ?
```
def get(self, name, default=None):
    return getattr(self, name, default)
```

This will prevent to use `get` as a field. As a consequence this name could not be used as a Capsul process parameter.

**Comment by denisri** [comment]
> Should we add a method on Controller to set a value unconditionally ?

Would it be useful ? It seems somewhat contradictory: validators are here to ensure that the values which are set actually conform to the expected constraints. If we have a function that bypass these constraints too easily, we cannot rely on validation and be assured that the values are OK. I assume this would be useful only in very specific and non-standard cases. So I would not expose such a function too visibly, and maybe the `object.__setattr__()` is enough ?

**Comment by denisri** [comment]
> Question : @denisri already mentioned that it is annoying to use `getattr(controller, name, default)` to get a possibly missing value of a controller field. What about adding the following method ?
> 
> ```
> def get(self, name, default=None):
>     return getattr(self, name, default)
> ```
> 
> This will prevent to use `get` as a field. As a consequence this name could not be used as a Capsul process parameter.

Maybe, but it would still imply to use a function (`x.get('name')` or `getattr(x, 'name', undefined)`) instead of the "pythonic" form `x.name`. `get()` is a bit shorter than `getattr(...)`, so why not, but on the other hand, for what it adds, is it worth adding a method to the API, or should we keep it as minimal and light as possible ?
Anyway the default would rather be `undefined` instead of `None`, I think.

**Comment by sapetnioc** [comment]
I asked previous question because I was not sure of the interest of these APi changes. I will not change anything to the controller API then.
