### ISSUE TITLE
The new controller (pydantic) gui does not allow to edit Controller instances

### ISSUE THREAD

**Issue by denisri** [populse/soma-base#20]
In the new pydantic_controller:
```
from soma.controller import Controller, field
from soma.qt_gui.controller import ControllerWidget

class C1(Controller):
    a: int = 2
    b: str
    c: str = 'no'

class C2(Controller):
    a: int = 0
    b: C1 = field(default_factory=C1)

cw = ControllerWidget(c2)
cw.show()
```
displays:
![controller](https://user-images.githubusercontent.com/1913468/160155530-20e5e2be-0368-4437-a02b-e187ece59af3.jpg)

so we cannot edit the sub-controller `c2.b`.

**Comment by denisri** [comment]
We cannot edit dicts either

**Comment by denisri** [comment]
it's fixed for `Controller`, it was just a typo in the factories keys.
For `dict` it seems not implemented at all.

**Comment by denisri** [comment]
I attempted to begin the dict controller GUI, but after writing some code, I realize that I don't master the controller GUI well enough to do it the right way. I fear to begin a series of bidouilles and warts.
We would really need some doc on the new GUI API and extension in order to use/develop it properly...

**Comment by sapetnioc** [comment]
Sorry for the delay, I forgot this ticket.

Yes, it is not obvious to guess how the GUI is working. A widget gui is using two classes that works together: `WidgetFactory` and `ControllerFieldInteraction`. The first one is responsible for Qt items creation and insertion in the container widget. The other manage all interactions with the controller (this allows notification when setting a value inside a list[list[...]]). I will document methods when I find the time.

**Comment by sapetnioc** [comment]
Some information about the customization of GUI for controllers: https://github.com/populse/soma-base/blob/pydantic_controller/doc/sphinx/gui_dev.rst

**Comment by sapetnioc** [comment]
Quickly tested the following code in branch `6.0`. Seems ok to me:

```
import sys

from soma.controller import Controller, field
from soma.qt_gui.controller import ControllerWidget
from soma.qt_gui.qt_backend.Qt import QApplication

class C1(Controller):
    a: int = 2
    b: str
    c: str = 'no'

class C2(Controller):
    a: int = 0
    b: C1 = field(default_factory=C1)

app = QApplication(sys.argv)

c2= C2()
cw = ControllerWidget(c2)
cw.show()

app.exec_()
```
