### ISSUE TITLE
Controller notification is incomplete

### ISSUE THREAD

**Issue by denisri** [populse/soma-base#37]
`Controller` notification is triggered when a field value is assigned. However for nested controllers, notification doesn't happen when a sub-controller is modified or assigned at a lower-level. We can setup callbacks in lover-level controllers but it is not always easy and convenient, especially in dynamic contexts.
The typical use is a field of type `list[Controller]`. Notification only happens when the full list is assigned, but when a list element is added, removed, or modified/reassigned, nothing happens. As list values are dynamic we cannot easily hook the insert/remove methods to setup callbacks on sub-items. Traits used to do so by replacing lists by subclasses if I remember.
I'm not even sure it is possible to fix this (except by replacing lists with `list` subclasses as in traits), but right now notification is, at least unreliable, not to say useless except for simple types. GUIs are not sync'd correctly, for instance.
Any ideas ?

**Comment by sapetnioc** [comment]
As far as I remember, this topic is only managed by GUI edition system. I you edit a list item in a GUI, other views are updated. However, if a list modification is done outside a GUI, I do not know any mean to get a notification by Python. Going towards a derivation of list seems, a priori, a bit complex. Do you think it is possible to list the use-cases where a list gets modified and to add an explicit list modification signal emission ?

**Comment by denisri** [comment]
What you say only partially works. Using:
```
from soma.controller import Controller
from soma.qt_gui.controller import ControllerWidget

class MyController(Controller):
    fl: list[str]

mc = MyController()
cw1 = ControllerWidget(mc)
cw2 = ControllerWidget(mc)
cw1.show()
cw2.show()
```
then when you add items in cw1 for instance, they actually do add in cw2, but the last value is not updated. Plus, when you modify an existing item value in cw1, it does not show up in cw2.
This is for `list[str]` items.
Now my use case is to manage the GUI for Capsul3 metadata attributes for iterations. The metadata object (`ProcessMetadata`) has high-level fields which correspond to schemas ("bids", "brainvisa", "shared"). Each of these fields value is a list (for a pipeline iteration) of `Controller` subclasses (`BIDSSchema` etc): the field type is `list[BIDSSchema]` here. User modifications in the GUI for the `ProcessMetadata` object are not notified at all. To be working we would need to add notification to each list item, which we cannot at the moment.

**Comment by sapetnioc** [comment]
If it is in the GUI is sounds like a bug to me. It was a bit long ago but I remember that I added a structure in GUI that kept track of the whole objects hierarchy and was connected both to GUI and controller. It is supposed to be the only interface for value modification by any GUI action and to properly raise signals for any other GUI listening. I will have to get back to the code to remember precisely how it is supposed to work.

**Comment by denisri** [comment]
In `BaseControllerWidget.update_inner_gui()`, the widget factory was looked for using `factory = self.factories.get(field)`. In `build()` however the factories are indexed using the key `field._dataclass_field`. If we use `factory = self.factories.get(field._dataclass_field)`, then the sync for `list[str]` is fixed.

**Comment by denisri** [comment]
It seems to work for `list[Controller]` too, but I have done other modifications before finding this fix, and I need to cancel them to see if this is enough.

**Comment by denisri** [comment]
It seems to work. I clean it up and commit.

**Comment by sapetnioc** [comment]
Well done. Thanks.
